python:
  - 2.7

gsl:
  - 2.4

numpy:
  - 1.14.0

boost:
  - 1.66

poco:
  - 1.7.3

pin_run_as_build:
  boost:
    max_pin: x.x
  eigen:
    max_pin: x.x
  hdf4:
    max_pin: x.x
  hdf5:
    max_pin: x.x
  gsl:
    max_pin: x.x
  openblas:
    max_pin: x.x
  blas:
    max_pin: x.x
  numpy:
    max_pin: x.x
  poco:
    max_pin: x.x
  nexus:
    max_pin: x.x
  jsoncpp:
    max_pin: x.x
  tbb:
    max_pin: x.x
  librdkafka:
    max_pin: x.x
  openssl:
    max_pin: x.x
