{% set version = "5.1.20210115.2323" %}
{% set git_rev = "03f045dd452ea02a2a32eeeb21ba4449ac0581c4" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - boost {{ boost }}
    - cmake
    - eigen
    - gsl
    - gxx_linux-64 7.3.* [linux64]
    - h5py
    - hdf4
    - hdf5
    - jsoncpp
    - librdkafka
    - muparser
    - nexus
    - ninja
    - numpy {{ numpy }}
    - openblas
    - openssl
    - pkg-config
    - poco
    - python {{ python }}
    - tbb-devel

  run:
    - boost {{ boost }}
    - h5py
    - librdkafka
    - nexus
    - numpy
    - openblas
    - poco
    - python
    - python-dateutil
    - pyyaml
    - scipy
    - six
    - tbb
    - gsl
    - jsoncpp
    - muparser
    - mkl

build:
  script_env:
    - CC
    - CXX
    - OSX_VERSION

test:
  imports:
    - mantid.kernel
    - mantid.geometry
    - mantid.api
    - mantid.simpleapi

about:
  home:
  license:
  license_file:
